# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ee7e69628d301a6b969153d31f2a6985"
name = "UPS Direct"
application_url = "https://ups-connector.onrender.com"
embedded = false

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_shipping,write_shipping"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://ups-connector.onrender.com/auth/callback",
  "https://ups-connector.onrender.com/auth/shopify/callback",
  "https://ups-connector.onrender.com/api/auth/callback"
]
